# Generated by Django 4.1.7 on 2023-03-15 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(blank=True, default=False, null=True)),
                ('user_closed', models.BooleanField(blank=True, default=False, null=True)),
                ('admin_closed', models.BooleanField(blank=True, default=False, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('ref_code', models.SlugField(blank=True, null=True, unique=True)),
                ('opened_date', models.DateTimeField(auto_now_add=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_admin', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
